### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by yangzhengxuan** [HennyNile/Notebooks#1]
请问在您看过的ALECE模型,您会换数据集吗

**Comment by HennyNile** [comment]
你好。首先我没有跑过ALECE的模型，也没有在该仓库中描述过ALECE。其次，我看到你的问题之后简单看了一下ALECE的仓库，看起来代码组织是比较规范的，通过读代码应该可以明白怎么修改workload。祝你一切顺利。

**Comment by yangzhengxuan** [comment]
好的谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qilong ***@***.***&gt;; 
发送时间: 2024年6月29日(星期六) 凌晨0:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HennyNile/helpful_notebook] 你好 (Issue #1)














 
你好。首先我没有跑过ALECE的模型，也没有在该仓库中描述过ALECE。其次，我看到你的问题之后简单看了一下ALECE的仓库，看起来代码组织是比较规范的，通过读代码应该可以明白怎么修改workload。祝你一切顺利。
